Repository wecode-bootcamp-korea/29-2nd-Airhnb-backend, pull requests merged in 2022-02, with the labels that each got.

#1 [주다희] 앱 생성 및 모델링
  airhnb/settings.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  houses/__init__.py
  houses/admin.py
  houses/apps.py
  houses/migrations/0001_initial.py
  houses/migrations/0002_initial.py
  houses/migrations/0003_alter_house_exit_alter_house_trap.py
  houses/migrations/0004_alter_house_user.py
  houses/migrations/__init__.py
  houses/models.py
  houses/tests.py
  houses/views.py
  reservations/__init__.py
  reservations/admin.py
  reservations/apps.py
  reservations/migrations/0001_initial.py
  reservations/migrations/__init__.py
  reservations/models.py
  reservations/tests.py
  reservations/views.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/0001_initial.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [주다희] 모델링 수정
  houses/migrations/0005_remove_ghost_house_house_ghost.py
  houses/models.py
Labels: Status: 리뷰 요청

#6 [주다희] 모델링 수정
  users/migrations/0002_alter_user_email_alter_user_name_and_more.py
  users/models.py
Labels: Status: 리뷰 요청

#3 29기 최형택 [ADD] Feature/Housedetail
  .gitignore
  airhnb/urls.py
  db_uploader.py
  houses/urls.py
  houses/views.py
  reservations/urls.py
  reservations/views.py
Labels: Status: 수정 요청

#7 [주다희] 카카오 소셜 로그인 기능 구현
  airhnb/urls.py
  requirements.txt
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#9 [주다희] 카테고리 리스트 get
  houses/models.py
  houses/urls.py
  houses/views.py
Labels: Status: 리뷰 요청

#5 [29기 강종범] Feature/being_the_host
  airhnb/settings.py
  airhnb/urls.py
  core/storages.py
  houses/tests.py
  houses/urls.py
  houses/views.py
Labels: Status: 리뷰 요청

#8 29기 최형택 [ADD] Feature/house reservation post
  .gitignore
  houses/views.py
  reservations/urls.py
  reservations/views.py
  users/migrations/0003_alter_user_birth_date.py
  users/models.py
Labels: Status: 리뷰 요청

#10 [주다희] 흉가 리스트 조회 기능 구현
  houses/urls.py
  houses/views.py
Labels: Status: Accepted

#11 [주다희] Modify: settings.py 변수 추가
  airhnb/settings.py
  users/views.py
Labels: Status: Accepted

#12 [29기 강종범][Modify] HouseTypeView, GhostView
  houses/views.py
Labels: Status: Accepted

#13 [최형택] 마이그레이션 수정 Feature/house reservation post
  houses/migrations/0005_remove_ghost_house_house_ghost 2.py
Labels: Status: Accepted
